### PR TITLE
Filter

### PR DESCRIPTION
**Pull request by shoshJacobs**

### CODE REVIEW

**Comment by shoshJacobs** [comment]
@mbrevda the others aren't issues, they are already on the branch but since i did a forced push- they all show up again... only the last two are new stuff and tests pass so all is ok. thanks!

**Comment by mbrevda** [comment]
Still dont get this git thing, huh?

**Comment by shoshJacobs** [comment]
nope, have to admit that I dont.

**Comment by shoshJacobs** [comment]
@mbrevda so what are we waiting for? is there anything I am suppose to do about the commits now that they are pushed?? if not, I need you to merge this all in so that I can run tests in demograph.

**Comment by mbrevda** [comment]
@shoshJacobs is this still pertinent?

**Pull request closed without merging**
